version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_DATABASE=book_db
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: academy-umbrela/quick-ns-api-client:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
volumes:
  db:

