server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: API-Core
          uri: lb://API-Core
          predicates:
            - Path=/book/**
        - id: API-Client
          uri: lb://API-Client
          predicates:
            - Path=/book-ad/**
