# Enable if config server enabled
#spring:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: CONFIGSERVER
#      failFast: true
#      username: someusername
#      password: somepassword

# Enable for security enabled microservices
#example:
#  baseUrl: http://localhost:8080
#  oauth2:
#    client:
#      grantType: client_credentials
#      clientId: {client-id}
#      clientSecret: {client-secret}
#      accessTokenUri: {issuer-uri}/v1/token
#      scope: custom_scope_book_db
